const shows=[
 {year:2001,network:'MTV',title:'TRL: Total Request Live',art:'TRL',tag:'MUSIC / LIVE',desc:'Countdowns, callers, and the loudest afternoon on television.'},
 {year:2003,network:'NBC',title:'The Office',art:'THE\nOFFICE',tag:'COMEDY / 22 MIN',desc:'A documentary crew catches the everyday drama of Dunder Mifflin.'},
 {year:2004,network:'Cartoon Network',title:'Adult Swim After Dark',art:'[as]',tag:'ANIMATION / LATE',desc:'The strange, surreal, and very late side of the schedule.'},
 {year:2006,network:'Discovery',title:'MythBusters',art:'MYTH\nBUSTERS',tag:'FACTUAL / 44 MIN',desc:'A little science, a lot of explosions, zero boring conclusions.'},
 {year:2008,network:'Comedy Central',title:'The Daily Show',art:'DAILY\nSHOW',tag:'NEWS / SATIRE',desc:'Headlines from a pre-streaming world, with a sharp left turn.'},
 {year:2011,network:'HBO',title:'Game of Thrones',art:'GOT',tag:'DRAMA / 60 MIN',desc:'The first watch, before anyone knew who to trust.'},
 {year:2013,network:'Netflix',title:'House of Cards',art:'HOC',tag:'DRAMA / 52 MIN',desc:'The dawn of the binge. One more episode was never one more.'},
 {year:2016,network:'Nickelodeon',title:'90s Are All That',art:'90s\nALL THAT',tag:'NOSTALGIA / 30 MIN',desc:'A throwback within a throwback: the late-night rerun block.'},
 {year:2018,network:'YouTube',title:'Creator Era',art:'▶',tag:'WEB / ON DEMAND',desc:'When the channel became the creator — and the feed never slept.'}
];
const networks=[['MTV','Music Television'],['NBC','National Broadcasting'],['Cartoon\nNetwork','Toons & More'],['Discovery','Discovery Channel'],['HBO','Home Box Office'],['Comedy\nCentral','Comedy Central'],['Nickelodeon','Nick at Nite'],['Netflix','Streaming'],['YouTube','Broadcast Yourself'],['FOX','Fox Broadcasting']];
const grid=document.querySelector('#showGrid'), networkGrid=document.querySelector('#networkGrid'), datePicker=document.querySelector('#datePicker');
function render(filter='all'){grid.innerHTML=''; const list=filter==='all'?shows:shows.filter(s=>filter==='2000'?s.year<2010:s.year>=2010); list.forEach((s,i)=>{const card=document.createElement('article');card.className='show-card';card.innerHTML=`<div class="show-top"><span>${String(s.year).slice(2)} / ${s.network}</span><span>↗</span></div><div class="show-art">${s.art.replace('\n','<br>')}<small>${i%2?'original':'rewind'}</small></div><div class="show-bottom"><div class="show-title">${s.title}</div><div class="show-meta">${s.tag}<br>PLAY ▶</div></div>`;card.addEventListener('click',()=>play(s));grid.appendChild(card)})}
function renderNetworks(){networks.forEach(([name,label])=>{const el=document.createElement('button');el.className='network';el.innerHTML=`<div class="network-logo">${name.replace('\n','<br>')}<span>${name==='MTV'?'music television':''}</span></div><div class="network-label">${label}</div>`;el.addEventListener('click',()=>{document.querySelectorAll('.network').forEach(n=>n.classList.remove('selected'));el.classList.add('selected');const match=shows.filter(s=>s.network.toLowerCase().includes(name.split('\n')[0].toLowerCase()));if(match.length){play(match[0]);document.querySelector('#playerSection').scrollIntoView({behavior:'smooth'})}});networkGrid.appendChild(el)})}
function play(show){document.querySelector('#playerTitle').textContent=show.title;document.querySelector('#playerDescription').textContent=show.desc;document.querySelector('#playerNetwork').textContent=`${show.network.toUpperCase()} · ${show.year} ARCHIVE FEED`;document.querySelector('#playerOverlay').style.display='none';document.querySelector('#playerSection').scrollIntoView({behavior:'smooth',block:'center'});document.querySelector('#videoPlayer').play().catch(()=>{})}
document.querySelectorAll('.era').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.era').forEach(b=>b.classList.remove('active'));btn.classList.add('active');render(btn.dataset.era);document.querySelector('#heroYear').textContent=btn.dataset.era==='2010'?'2014':btn.dataset.era==='2000'?'2004':'2009'}));datePicker.addEventListener('change',e=>{const year=new Date(e.target.value).getFullYear();const era=year<2010?'2000':'2010';document.querySelector(`[data-era="${era}"]`).click();document.querySelector('#heroYear').textContent=year});document.querySelector('#randomBtn').addEventListener('click',()=>play(shows[Math.floor(Math.random()*shows.length)]));document.querySelector('#aboutBtn').addEventListener('click',()=>document.querySelector('#about').scrollIntoView({behavior:'smooth'}));render();renderNetworks();
